### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by davidADSP** [RoboEden/Luxai-s2-Baseline#2]
Hey!

Could you include a `requirements.txt` so that we know which versions of `gym` / `torch` this is compatible with?

I see it's using `gym` rather that `gymansium` and also that `env.seed(x)` is used so must be pre v26 of `gym`.

Thanks!

**Comment by yk7333** [comment]
Hi!

We have included our requirements in ```environment.yml```. To set up a conda environment based on these specifications, simply run: ```conda env create -f environment.yml```. Within this file, you'll also find the versions for ```gym``` and other dependent libraries.

Hope this helps!

**Comment by StoneT2000** [comment]
A few people on Kaggle have brought up this issue. Would it be super difficult to just upgrade to gymnasium?

**Comment by Schopenhauer-loves-Hegel** [comment]
We have recently updated the Baseline for the new gymnasium version. You can access the code here: https://github.com/RoboEden/Luxai-s2-Baseline/tree/main/Luxai-s2-Baseline4gymnasium.
