### ISSUE TITLE
Are any modifications needed for neurips stage? 

### ISSUE THREAD

**Issue by wonjun-dev** [RoboEden/Luxai-s2-Baseline#3]
I followed README instructions, but i got a lot of assertion error on python train.py.

I modified map_size 48 to 64 and it resolves assertion error, but i faced value error: 

 File "/sources/Luxai-s2-Baseline/luxenv.py", line 329, in reset
    obs, rewards, dones, infos = self.proxy.step(actions)
ValueError: too many values to unpack (expected 4) 

Modification of 329th line of luxenv.py 
obs, rewards, dones, _, infos = self.proxy.step(actions)
resloves the error, but it raised the other error

 File "/opt/conda/envs/luxai_s2/lib/python3.8/site-packages/numpy/core/shape_base.py", line 471, in stack
    return _nx.concatenate(expanded_arrays, axis=axis, out=out,
  File "<__array_function__ internals>", line 200, in concatenate
ValueError: Output array is the wrong shape

**Comment by Schopenhauer-loves-Hegel** [comment]
The map_size issue has been fixed today and you can access the code here for gymnasium version: https://github.com/RoboEden/Luxai-s2-Baseline/tree/main/Luxai-s2-Baseline4gymnasium.

**Comment by wonjun-dev** [comment]
Thanks for your supporting!
